object Modules {
    const val coreApi = ":modules:celebrity:core:api"
    const val coreFactory = ":modules:celebrity:core:factory"
    const val coreImpl = ":modules:celebrity:core:impl"
    const val activityContainer = ":modules:features:activity-container"
    const val splash = ":modules:features:splash"
    const val bottomNavigationContainerApi = ":modules:features:bottom-navigation-container:api"
    const val bottomNavigationContainerImpl = ":modules:features:bottom-navigation-container:impl"
    const val teams = ":modules:features:teams"
    const val heroes = ":modules:features:heroes"
    const val items = ":modules:features:items"
    const val inDota = ":modules:features:in_dota"
    const val openDotaApi = ":modules:base:open_dota_api"
    const val ui = ":modules:base:ui"
    const val network = ":modules:base:network"
    const val databases = ":modules:base:databases"
}